### Server
GET http://37.27.179.21:8080/api/series/getallseries
username: Hovedopgave
password: TtXr@oA7M.PaNxCmsvL2WBMw

### Local for development
GET http://localhost:5203/api/series/getallseries
username: Hovedopgave
password: TtXr@oA7M.PaNxCmsvL2WBMw

###

POST http://localhost:5203/api/stock/poststockupdates
Content-Type: application/json
[
  {
    "sku": "100001001-36",
    "stock": 420,
    "size": 0
  }
]
